export default function Blog() {
  return (
    <main className="
        flex
        w-full
        max-w-full
        flex-col 
        items-center
        justify-center
        sm:pt-12 
        lg:w-[85%] 
        xl:w-[75%] 
        "
      >
        <div
          className="
        flex 
        flex-col 
        items-center 
        justify-center 
        py-8
        "
        >
          <h1
            className={`
          flex 
          w-full 
          max-w-full
          items-center 
          justify-center
          text-center
          font-proximaSemiBold
          text-4xl
          uppercase
          text-seaBlue-700
          sm:text-5xl
          lg:text-6xl
          `}
          >
            PoSciDonDAO's Blog
          </h1>
          <p
            className="
            flex
            w-[70%]
            items-center 
            justify-center 
            py-8 
            text-center 
            text-base 
            sm:text-lg
            xl+:w-[50%]
          "
          >

          </p>
        </div>
    </main>
  );
}
